### ISSUE TITLE
scenario_parser reports file not found on xml ending tag mismatch

### ISSUE THREAD

**Issue by luxiya01** [patrykcieslak/stonefish#20]
**Describe the bug**
I accidentally created an environment file with a mismatching XML ending tag (`<dimensions xyz="0.0 0.0 0.0">`). The stonefish_ros_parser.log file logged the error `"File not found!"`, but perhaps `"XML file syntax error"` would be a more informative error message?

**Comment by patrykcieslak** [comment]
Thanks for pointing it out! I have fixed the issue. Cheers
