### ISSUE TITLE
GPS reports zero longitude and latitude when configuring a negative longitude for the environment

### ISSUE THREAD

**Issue by mzhouURI** [patrykcieslak/stonefish#30]
GPS sensor reports 0 longitude and 0 latitude when setting negative longitude in the scenario file for the <environment>.

**To Reproduce**
1. Install stonefish
2. Install cola2_msgs
3. install_stonefish_ros
4. install_cola2_stonefish
5. change line 2 and 3 in `stonefish_ros/launch/simulator.launch`
```
    <arg name="simulation_data" default="$(find cola2_stonefish)/data"/> <!-- path to the data directory -->
    <arg name="scenario_description" default="$(find cola2_stonefish)/scenarios/sparus2_tank.scn"/> 
```
6. change the longitude to a negative value at line 4 in `cola2_stonefish/scenarios/sparus2_tank.scn`

   `<ned latitude="41.7777" longitude="-3.0333"/>`

8.  `roslaunch stonefish_ros simulator.launch`

9. `rostopic echo /sparus2/navigator/gps` in a separated terminal window

**Expected behavior**
latitude and longitude reports 0.0 
see the attached screenshot

**Screenshots**
![gps_invalid](https://user-images.githubusercontent.com/57601376/209844709-9ae98ab3-4508-4b77-b43f-8ce1f9ad0959.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by patrykcieslak** [comment]
Thank you for reporting the issue and describing it nice.
It should be now fixed. Please update the stonefish_ros too, becasue the error was in both.
