### ISSUE TITLE
about Current function

### ISSUE THREAD

**Issue by seunghh1313** [patrykcieslak/stonefish#46]
I have experienced and am grateful for many things through your simulation.

While using the simulation, I had a question. There is a function that allows you to add water velocity to the environment, so I added water velocity to the ocean tag in the scenario file environment, but this does not seem to work. I need help with this part.
Thank you.
![testcurrent](https://github.com/patrykcieslak/stonefish/assets/127174282/f7b847f2-965d-4771-a370-3e699bf3e59d)

**Comment by Michele1996** [comment]
Hello @seunghh1313 , I think the currents are just disabled by default. You can use a service to enable them

**Comment by seunghh1313** [comment]
Thank you very much I solved this issue!
