### ISSUE TITLE
Add arg tag for include in `scn` files

### ISSUE THREAD

**Issue by nilsbore** [patrykcieslak/stonefish#7]
**Is your feature request related to a problem? Please describe.**
We would like to be able to include multiple robots of the same type from an `scn` file, something like this:
```
<scenario>

    <include file="$(find sam_stonefish_sim)/data/biograd_world/biograd_env.scn"/>
    <include file="$(find sam_stonefish_sim)/data/sam_auv/sam_auv.xml">
       <arg name="robot_name" value="sam1"/>
    </include>
    <include file="$(find sam_stonefish_sim)/data/sam_auv/sam_auv.xml">
       <arg name="robot_name" value="sam2"/>
    </include>

</scenario>
```

**Describe the solution you'd like**
We would add an arg tag like above that would be necessary when including a file that has a line like this at the top:
`<arg name="robot_name"/>`
There would probably be NO default value like in ROS launch files, just to keep things simple. This means you always have to provide arg when including.

**Describe alternatives you've considered**
The alternative in this case is to make several copies of our robot `scn` file with different robot names. That seems like a worse solution.

**Additional context**

**Comment by patrykcieslak** [comment]
I have added now this functionality in the parser class.

Cheers!
